kind: pipeline
name: backend

steps:
- name: verify & build
  image: golang
  commands:
  - cd be
  - go vet ./...
  - go build ./cmd/main.go
  when:
    branch:
      include:
      - main
- name: build docker image
  image: plugins/docker
  settings:
    username: philanton
    password:
      from_secret: docker_password
    repo: philanton/todo-be
    dockerfile: be/Dockerfile
    context: be

trigger:
  event:
  - push
---
kind: pipeline
name: frontend

steps:
- name: verify & build
  image: node
  commands:
  - cd fe
  - npm install
  - npm run build
  when:
    branch:
      include:
      - main
- name: build docker image
  image: plugins/docker
  settings:
    username: philanton
    password:
      from_secret: docker_password
    repo: philanton/todo-fe
    dockerfile: fe/Dockerfile
    context: fe

trigger:
  event:
  - push
